config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path

from . import views


app_name = "rooms"

urlpatterns = [
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse

from django_countries.fields import CountryField

from core import models as core_models


class AbstractItem(core_models.AbstractTimeStamped):

    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """ RoomType Model Definition """

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition """

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.AbstractTimeStamped):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")

    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.AbstractTimeStamped):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)

    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0

        if len(all_reviews) == 0:
            return "N/R"
        else:
            for review in all_reviews:
                all_ratings += review.rating_average()

            return round(all_ratings / len(all_reviews), 2)

    def get_first_photo(self):
        (photo,) = self.photos.all()[:1]

        return photo.file.url

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]

        return photos

rooms/forms.py
from django import forms

from django_countries.fields import CountryField

from . import models


class SearchFrom(forms.Form):
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        queryset=models.RoomType.objects.all(), empty_label="Any Kind", required=False
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

rooms/views.py
from django.views.generic import ListView, DetailView, View, UpdateView
from django.shortcuts import render
from django.core.paginator import Paginator

from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class RoomDetailView(DetailView):

    """ RoomDetail Definition"""

    model = models.Room


class SearchView(View):

    """ SearchView Definition """

    def get(self, request):
        country = request.GET.get("country")

        if country:
            form = forms.SearchFrom(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city
                    # city가 자기 멋대로 바뀜 오류 수정 필요

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                print(paginator)
                print("=" * 5)
                print(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchFrom()
            print("hi")

        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = {
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "house_rules",
        "facilities",
    }

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        print(room.host.pk, self.request.user.pk)
        print(vars(self.request))

        return room
    # 3분 6초

templates/rooms/room_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{{% block content %}
    <div class="-mt-5 container max-w-full h-50vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center" style="background-image:url({{room.get_first_photo}});"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image: url({{photo.file.url}});" class="w-1/2 h-auto bg-cover bg-center border border-gray-500"></div>
            {% endfor %}
        </div>
    </div>
    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                    {% include 'mixins/user_avatar.html' with user=room.host %}
                    <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            <div class="flex border-section">
                <span class="mr-5 font-light">{{room.room_type}}</span>
                <span class="mr-5 font-light">{{room.beds}} bed{{room.beds|pluralize}}</span>
                <span class="mr-5 font-light">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
                <span class="mr-5 font-light">{{room.baths}} bath{{room.baths|pluralize}}</span>
                <span class="mr-5 font-light">{{room.guests}} guest{{room.guests|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>

                
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{a.name}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{f.name}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                
                {% for h in room.house_rules.all %}
                    <li class="mb-2">{{h.name}}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-teal-500"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include 'mixins/user_avatar.html' with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container xl:w-1/4 lg:w-5/12 md:w-1/2 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Update Room" %}
    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}

    <div class="container mx-auto pb-10">
        <div class="rounded-xl bg-gray-800 h-50vh mt-32 mb-24 mx-8 bg-center bg-cover" style="background-image: url(https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format);"></div>

        <div class="flex flex-wrap mx-8 mb-10">
            {% for room in rooms %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
        
        <div class="flex items-center mx-auto container justify-center">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
            
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>
    
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <h2>Search</h2>

    <form method="get" action="{% url "rooms:search" %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{room.name}}</h3>
    {% endfor %}

{% endblock content %}